"""empty message

Revision ID: 0bfb94bbdb5b
Revises: fc1e204c5ec4
Create Date: 2020-08-07 21:59:56.757825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bfb94bbdb5b'
down_revision = 'fc1e204c5ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('staff_username', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'portfolio', ['staff_username'])
    op.create_foreign_key(None, 'portfolio', 'staff', ['staff_username'], ['username'])
    op.create_unique_constraint(None, 'staff', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='unique')
    op.drop_constraint(None, 'portfolio', type_='foreignkey')
    op.drop_constraint(None, 'portfolio', type_='unique')
    op.drop_column('portfolio', 'staff_username')
    # ### end Alembic commands ###
