"""empty message

Revision ID: 2716da4327fa
Revises: 0bfb94bbdb5b
Create Date: 2020-08-07 22:13:58.197909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2716da4327fa'
down_revision = '0bfb94bbdb5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('staff_username', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'portfolio', ['staff_username'])
    op.create_foreign_key(None, 'portfolio', 'staff', ['staff_username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolio', type_='foreignkey')
    op.drop_constraint(None, 'portfolio', type_='unique')
    op.drop_column('portfolio', 'staff_username')
    # ### end Alembic commands ###
