"""empty message

Revision ID: 49f9d5a8abdc
Revises: d9dbc681c692
Create Date: 2020-08-07 21:07:14.456351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f9d5a8abdc'
down_revision = 'd9dbc681c692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'password')
    # ### end Alembic commands ###
