"""empty message

Revision ID: a08dcb811e3b
Revises: ae65e3b88d64
Create Date: 2020-08-07 21:42:32.905616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08dcb811e3b'
down_revision = 'ae65e3b88d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('staff_username', sa.String(), nullable=True))
    op.create_foreign_key(None, 'portfolio', 'staff', ['staff_username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolio', type_='foreignkey')
    op.drop_column('portfolio', 'staff_username')
    # ### end Alembic commands ###
