"""empty message

Revision ID: ae65e3b88d64
Revises: 49f9d5a8abdc
Create Date: 2020-08-07 21:29:22.120276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae65e3b88d64'
down_revision = '49f9d5a8abdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('staff_username', sa.String(), nullable=True))
    op.create_foreign_key(None, 'portfolio', 'staff', ['staff_username'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolio', type_='foreignkey')
    op.drop_column('portfolio', 'staff_username')
    # ### end Alembic commands ###
