"""empty message

Revision ID: bf782fab9427
Revises: d01b13b4f4be
Create Date: 2020-08-06 00:01:12.821244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf782fab9427'
down_revision = 'd01b13b4f4be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('message', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('subtitle', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('featured_image', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_entry_timestamp'), 'entry', ['timestamp'], unique=False)
    op.create_table('portfolio',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('basic', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('expertise', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('skill', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('experience', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('education', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('projects', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('social', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('post_slug', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['post_slug'], ['entry.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('portfolio')
    op.drop_index(op.f('ix_entry_timestamp'), table_name='entry')
    op.drop_table('entry')
    op.drop_table('staff')
    op.drop_table('contacts')
    # ### end Alembic commands ###
