"""empty message

Revision ID: d117f01359af
Revises: db96fe1c2f9d
Create Date: 2020-08-08 08:37:52.280788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd117f01359af'
down_revision = 'db96fe1c2f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'entry', 'staff', ['staff_id'], ['id'])
    op.create_foreign_key(None, 'portfolio', 'staff', ['staff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolio', type_='foreignkey')
    op.drop_constraint(None, 'entry', type_='foreignkey')
    op.drop_table('staff')
    # ### end Alembic commands ###
