"""empty message

Revision ID: d9dbc681c692
Revises: 7849e7aa8abd
Create Date: 2020-08-07 21:06:44.724151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9dbc681c692'
down_revision = '7849e7aa8abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('password', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
