"""empty message

Revision ID: db96fe1c2f9d
Revises: 2716da4327fa
Create Date: 2020-08-07 22:15:18.111126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db96fe1c2f9d'
down_revision = '2716da4327fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('staff_username', sa.String(), nullable=False))
    op.create_foreign_key(None, 'portfolio', 'staff', ['staff_username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolio', type_='foreignkey')
    op.drop_column('portfolio', 'staff_username')
    # ### end Alembic commands ###
